apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-xe
spec:
  serviceName: oracle
  replicas: 1
  selector:
    matchLabels:
      app: oracle-xe
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle
          image: gvenzl/oracle-xe:21.3.0-slim
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: ORACLE_PASSWORD
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: ORACLE_USER
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: ORACLE_PASSWORD
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
          
  volumeClaimTemplates:
    - metadata:
        name: oracle-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-premium
        resources:
          requests:
            storage: 5Gi
