CREATE TABLE incidents
(
    id           NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      NUMBER(38, 0),
    title        VARCHAR2(255),
    status       VARCHAR2(255),
    type         VARCHAR2(255),
    description  VARCHAR2(255),
    localization VARCHAR2(255),
    CONSTRAINT pk_incidents PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR2(255),
    password    VARCHAR2(255),
    role        VARCHAR2(255),
    document_id VARCHAR2(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE incidents
    ADD CONSTRAINT FK_INCIDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);