apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-system
  namespace: staging
  labels:
    app: security-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-system
  template:
    metadata:
      labels:
        app: security-system
    spec:
      containers:
        - name: app
          image: fabiodinizdev/security-system:staging 
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:oracle:thin:@oracle.staging.svc.cluster.local:1521/XEPDB1
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: ORACLE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-credentials
                  key: ORACLE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: oracle.jdbc.OracleDriver
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
