apiVersion: v1
kind: Service
metadata:
  name: security-system-staging-service
spec:
  selector:
    app: security-system
    env: staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
