apiVersion: v1
kind: ConfigMap
metadata:
  name: security-system-config
  namespace: production
data:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.production.svc.cluster.local:1521/XEPDB1
  application.properties: |
    spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.format_sql=true
    spring.flyway.locations=classpath:db/migration
    spring.flyway.baseline-on-migrate=true
