apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-system-prod
  labels:
    app: security-system
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security-system
      env: production
  template:
    metadata:
      labels:
        app: security-system
        env: production
    spec:
      containers:
        - name: security-system-app
          image: fabiodinizdev/security-system:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:oracle:thin:@2804:4b0:1200:5d00:e5a3:ca39:6903:f1d:9445/XEPDB1
            - name: SPRING_DATASOURCE_USERNAME
              value: test
            - name: SPRING_DATASOURCE_PASSWORD
              value: test
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: oracle.jdbc.OracleDriver
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
