CREATE TABLE employees
(
    id          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role        VARCHAR2(255),
    document_id VARCHAR2(255),
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

ALTER TABLE incidents
    ADD employee_id NUMBER(38, 0);

ALTER TABLE incidents
    ADD CONSTRAINT FK_INCIDENTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);
