name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn clean package

      - name: Verificar arquivos em target
        run: ls -la target


      - name: Executar testes
        run: mvn test

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t fabiodinizdev/security-system:latest .
          docker tag fabiodinizdev/security-system:latest fabiodinizdev/security-system:staging

      - name: Push da imagem
        run: docker push fabiodinizdev/security-system:latest
             docker push fabiodinizdev/security-system:staging

  deploy_staging:
    name: Deploy no ambiente de staging
    runs-on: ubuntu-latest
    needs: build_test_and_push
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy Staging
        run: |
          kubectl apply -f k8s/staging/deployment.yaml
          kubectl apply -f k8s/staging/service.yaml
    
      -  name: Verificacao de pods e serviços
         run: |
          echo "Verificando pods"
          kubectl get pods
          echo "Verificando serviços"
          kubectl get svc
  

  deploy_production:
    name: Deploy no ambiente de produção
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy Produção
        run: |
          kubectl apply -f k8s/production/deployment.yaml
          kubectl apply -f k8s/production/service.yaml
      
      -  name: Verificacao de pods e serviços
         run: |
          echo "Verificando pods"
          kubectl get pods
          echo "Verificando serviços"
          kubectl get svc
   